### ISSUE TITLE
Allow Pushing Mobs to Avoid getting Stuck behind door

### ISSUE THREAD

**Issue by ardissaps** [Traben-0/solid_mobs#1]
Hello sir thank you for the good mods!
Would you like to add ability to push mobs a little when we wallking toward them (off course not to murder them on the edge of the cliff hahaha, joking). Thus can help us when we stuck inside like house and they stand on the door instead of killing them we can push them little :V .

**Comment by Traben-0** [comment]
I have just released version 1.3 with a shove mechanic to help with getting stuck :)
