### ISSUE TITLE
Entity "Falling_Block" causes ticking entity crash when landing on another entity.

### ISSUE THREAD

**Issue by Tavreth** [Traben-0/solid_mobs#12]
If you summon a falling sand block and have it drop down onto a mob (i.e. a Zombie), it will crash the game/server.
It won't crash if you disable shared falling damage.

<details>
  <summary>Crash Report</summary>
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-02-18 17:32:27
Description: Ticking entity

java.lang.NoSuchFieldError: field_5847
	at net.minecraft.class_2248.handler$boj000$etf$fallDamageRedirect(class_2248.java:2204)
	at net.minecraft.class_2248.method_9554(class_2248.java)
	at net.minecraft.class_1297.method_5623(class_1297.java:1181)
	at net.minecraft.class_1297.method_5784(class_1297.java:682)
	at net.minecraft.class_1540.method_5773(class_1540.java:137)
	at net.minecraft.class_3218.method_18762(class_3218.java:728)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2248.handler$boj000$etf$fallDamageRedirect(class_2248.java:2204)
	at net.minecraft.class_2248.method_9554(class_2248.java)
	at net.minecraft.class_1297.method_5623(class_1297.java:1181)
	at net.minecraft.class_1297.method_5784(class_1297.java:682)
	at net.minecraft.class_1540.method_5773(class_1540.java:137)
	at net.minecraft.class_3218.method_18762(class_3218.java:728)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)

-- Entity being ticked --
Details:
	Entity Type: minecraft:falling_block (net.minecraft.class_1540)
	Entity ID: 2149
	Entity Name: Falling Block
	Entity's Exact location: -58.50, 77.32, -81.50
	Entity's Block location: World: (-59,77,-82), Section: (at 5,13,14 in -4,4,-6; chunk contains blocks -64,-64,-96 to -49,319,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.23, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Immitating BlockState: Block{gigeresque:acid_block}[thickness=1,waterlogged=false]
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Tavreth'/202, l='ServerWorld minecraft:overworld world', x=214.97, y=63.63, z=-511.25]]
	Chunk stats: 4050
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,87,0), Section: (at 0,7,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 48288 game time, 48288 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 806469632 bytes (769 MiB) / 3716153344 bytes (3544 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c8d
	Graphics card #0 versionInfo: DriverVersion=24.21.13.9836
	Graphics card #1 name: Intel(R) HD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x591b
	Graphics card #1 versionInfo: DriverVersion=31.0.101.2111
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 13174.15
	Virtual memory used (MB): 7903.22
	Swap memory total (MB): 5120.00
	Swap memory used (MB): 155.21
	JVM Flags: 1 total; -Xmx4G
	Fabric Mods: 
		architectury: Architectury 7.1.70
		azurelib: AzureLib 1.0.2
			com_eliotlash_mclib_mclib: mclib 20
		bestylewither: BE Style Wither 1.4.2
		bookshelf: Bookshelf 17.0.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.5.1-1.19.3
			maelstrom_library: Maelstrom Library 1.4-1.19.3-rc1
			multipart_entities: MultipartEntities 1.3-1.19.3-rc1
		botanypots: BotanyPots 10.0.2
		botanytrees: BotanyTrees 6.0.1
		cardinal-components: Cardinal Components API 5.1.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-block: Cardinal Components API (blocks) 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
		carryon: Carry On 2.0.4.15
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.1
		charmofundying: Charm of Undying 6.2.1+1.19.3
		chas: Craftable Horse Armour & Saddle 1.19-1.9-Fabric
		clay: Clay Soldiers 0.4.3
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.48
		continents: Continents 1.1
		cotw: Curse Of The Warden 1.0.0
		customspawns: Custom Spawns 0.7+1.19.3
		darkwaters: Dark Waters 0.0.12
		daylight_mobs_reborn: Daylight Mobs Reborn 1.2.5
		doubledoors: Double Doors 4.2
		dragonfight: Dragonfight Mod 1.19.3-3.7
		dusk: Dusk Mod 1.19.3-3.2
		elementalcreepers: Elemental Creepers: Refabricated 1.4.3+1.19.3
			yet-another-config-lib: YetAnotherConfigLib 2.1.1
		fabric-api: Fabric API 0.73.2+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.1+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.2.1+06937c4b85
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.41+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.44+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.10+312c329485
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.12+1134c5b885
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.20+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.24+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.14+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.31+49abcf7e85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.1+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.5+1134c5b885
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.3+1134c5b885
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.5+a91e48b785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+5b9a588b85
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.14
		forgeconfigapiport: Forge Config API Port 5.0.9
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		geckolib: Geckolib 4.0.3
		giantspawn: Giant Spawn 4.3
		gigeresque: Gigeresque 0.5.6
		huskspawn: Husk Spawn 3.3
		illagerslovearmor: IllagersLoveArmor 1.0.1+1.19.3
		immersive_portals: Immersive Portals 2.5.1
			imm_ptl_core: Immersive Portals Core 2.5.1
			q_misc_util: QMiscUtil 2.5.1
		incendium: Incendium 5.1.4
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 12.2.0.16
		kiwi: Kiwi Lib 9.1.1
		lithium: Lithium 0.10.4
		mavapi: More Axolotl Variants API 1.0.3
		mavm: More Axolotl Variants Mod 1.2.1
		mca: Minecraft Comes Alive 7.4.5+1.19.3
		mcwbridges: Macaw's Bridges 2.0.6
		mcwdoors: Macaw's Doors 1.0.8
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwlights: Macaw's Lights and Lamps 1.0.5
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.2
		mcwroofs: Macaw's Roofs 2.2.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.8
		mcwwindows: Macaw's Windows 2.1.2
		midnightlib: MidnightLib 1.1.0
		minecraft: Minecraft 1.19.3
		more_babies: More Babies 1.0.1
		mru: Mineblock's Repetition Utilities 0.1.5+1.19.3
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		nochatreports: No Chat Reports 1.19.3-v2.0.0
		nullscape: Nullscape 1.2
		omnihopper: Omni-Hopper 1.2.0+1.19.3
			cooldown-coordinator: Cooldown Coordinator 0.4.3
		passablefoliage: Passable Foliage 1.19.3-fabric-6.0.0
		peepingcreepers: Peeping Creepers 1.2-1.18-1.19
		quicksort: Quicksort 0.3.0+1.19.3
		realisticbees: Realistic Bees 3.3
		sextant: Immersive Travel Overhaul 1.02_pre
		skeletonhorsespawn: Skeleton Horse Spawn 3.4
		smartbrainlib: SmartBrainLib 1.8
		solid_mobs: Solid Mobs 1.6
		spidersproducewebs: Spiders Produce Webs 3.1
		starlight: Starlight 1.1.1+fabric.ae22326
		strayspawn: Stray Spawn 3.3
		structory: Structory 1.0.1
		structory_towers: Structory: Towers 1.0.0
		terralith: Terralith 2.3
		trinkets: Trinkets 3.5.1
		vivecraft: Vivecraft 1.19.3-0.0.13
		weaponmaster: YDM's Weapon Master 3.0.5
		woof: Woof 3.0.0-1.19.3
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			owo: oωo 0.9.3+1.19.3
				blue_endless_jankson: jankson 1.2.1
		yigd: You're in Grave Danger 1.5.1
		zombiehorsespawn: Zombie Horse Spawn 4.4
	Server Running: true
	Player Count: 1 / 20; [class_3222['Tavreth'/202, l='ServerWorld minecraft:overworld world', x=214.97, y=63.63, z=-511.25]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
</details>

**Comment by Traben-0** [comment]
fixed in 1.6.2, which is only on MC 1.18.2 for the moment, will mark resolved once the i get that fix through to modern versions

**Comment by Traben-0** [comment]
fixed in version 1.7
