### ISSUE TITLE
Suggestion: platform/scaffolding-like collision

### ISSUE THREAD

**Issue by TheFurryDevil** [Traben-0/solid_mobs#15]
Basically making entities only collide with mobs if they are above them, like scaffolding, or platforms in 2D games.
Additionally the player can choose to drop through by sneaking (and jumping) much like with scaffolding.

I don't know if you can re-use scaffolding collision code or something, but disabling the collision while an entity's bounding box is not above the collidable entity's bounding box, or while attempting to drop through, should work too.

**Comment by Traben-0** [comment]
added in version 1.7
