### ISSUE TITLE
Crash when shift+right clicking on mobs

### ISSUE THREAD

**Issue by dbrighthd** [Traben-0/solid_mobs#17]
disabling mob shoving makes the crash not happen (as talked about in the discord)

[crash-2023-07-17_14.38.16-client.txt](https://github.com/Traben-0/solid_mobs/files/12074901/crash-2023-07-17_14.38.16-client.txt)

**Comment by LIXFERSI** [comment]
Fix coming?

**Comment by Traben-0** [comment]
fixed in version 1.7
