### ISSUE TITLE
Zombie cannot attack mob below him

### ISSUE THREAD

**Issue by slava110** [Traben-0/solid_mobs#2]
Zombie cannot reach this villager. It's so sad :c
Do you think it is possible to make this zombie happy? Maybe he should be able to attack mobs below him
![изображение](https://user-images.githubusercontent.com/26705162/173820058-5dcf21bf-b949-4628-ab39-a78319c767c3.png)

**Comment by Traben-0** [comment]
i'll look into it

**Comment by Traben-0** [comment]
I have just released version 1.3 with a fix for this :)

**Comment by slava110** [comment]
Thanks! Zombie finally got him c:
![изображение](https://user-images.githubusercontent.com/26705162/174451345-cc23c3a3-6a47-4571-9a64-f0a9955510b0.png)
