### ISSUE TITLE
[Crash] [PLS] Ice and Fire - java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Cixon** [Traben-0/solid_mobs#20]
### Crash Report:
[crash-2023-08-30_21.52.24-server.txt](https://github.com/Traben-0/solid_mobs/files/12481746/crash-2023-08-30_21.52.24-server.txt)

### Log (line 2,682):
[latest.log](https://github.com/Traben-0/solid_mobs/files/12481750/latest.log)

-
1.18.2 / FML 40.2.8
version forge v1.7

**Comment by Traben-0** [comment]
Should be a quick fix I'll see about getting one out tonight

**Comment by Cixon** [comment]
awesome. i highly appreciate the support on older versions

**Comment by Traben-0** [comment]
fixed in version 1.7.1
