### ISSUE TITLE
more accurate hitbox option.

### ISSUE THREAD

**Issue by BookWyrm114** [Traben-0/solid_mobs#4]
A way for mobs to have a hitbox that's alot more accurate to the actual model of the entity, rather than just cube hitboxes

**Comment by Traben-0** [comment]
that would be a **VERY** signifigant rework of hitboxes, not something i'm planning on doing, though if a mod did it i'd happily support that

**Comment by Flaming-skeleton-guitar** [comment]
https://modrinth.com/mod/countereds-accurate-hitboxes
This mod seems to do something similar, though it is made for hitting entities rather than colliding with them
