### ISSUE TITLE
[1.19] Incompatibility with Wall Jump

### ISSUE THREAD

**Issue by Flypaste** [Traben-0/solid_mobs#5]
Installing solid mobs with [wall jump](https://www.curseforge.com/minecraft/mc-mods/wall-jump-unofficial-fabric) causes wall clinging to not function anymore. This wall jump mod also has a sprint speed boost, which I have disabled, but it's also causing an incompatibility with solid mobs where the player stops sprinting when they lose contact with the ground and need to refresh their sprint.

**Comment by Traben-0** [comment]
I'll look into this, I have an idea of the cause

**Comment by dangbroitsdon** [comment]
Alright, after debugging for a couple days I have figured out what is causing the issues it has something to do with calling this part

`!(IsInvisible())`

Of this variable (in the first etf$collisionOverride inside your MixinEntity)

`returnValue = isAlive() && !(!solidMobsConfigData.allowInvisibleCollisions && isInvisible());`

As to why these issues happen, perhaps something to do with block and particle collision, but I'm not entirely sure on that one

In my testing, I found out that if you put !isInvisible behind an If statement of allowInvisibleCollision, and have allowInvisibleCollision set to false then you can use Wall Jump simultaneously with Solid Mobs but that would also mean if !
(isInvisible) is set to true it would just cause the same issues again. 

Hope this helps you come up with a solution that is perhaps better then that unless you want to use that but idk

**Comment by Traben-0** [comment]
very strange, I will be sure to code in compatability to disable that setting if wall jump is present

**Comment by dangbroitsdon** [comment]
Sounds great!

**Comment by Traben-0** [comment]
testing it myself the isInvisible() call seems to have no impact on the issue, completely removing all calls to it has no effect

**Comment by dangbroitsdon** [comment]
unfortunate, try setting the return value to false outside of ```if(solidMobsConfigData.canUseMod(this.getWorld()))```, I tested it just now and it fixed it fully in my case.

**Comment by Traben-0** [comment]
will look into these thanks for the help

**Comment by dangbroitsdon** [comment]
don't mention it! though, apologizes for not helping sooner.

**Comment by Traben-0** [comment]
added in version 1.7
