### ISSUE TITLE
Crash with ItemPhysics mod

### ISSUE THREAD

**Issue by IntMarco** [Traben-0/solid_mobs#7]
If u have Solid Mobs with an Item Physics mod, like ItemPhysics Full or Interact game crashes when loading.

**Comment by Traben-0** [comment]
Can I get the crash log?

**Comment by Traben-0** [comment]
I cannot replicate this with https://www.curseforge.com/minecraft/mc-mods/itemphysic please provide a crash log and reopen this issue if it happens again
